#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Remove old polyMesh
rm -rf constant/polyMesh

# Create base mesh
runApplication blockMesh

# Create cell sets for the cuts
runApplication topoSet

# Delete the cells in the cuts to create the obstacles
runApplication subsetMesh cut1 -patch walls -overwrite

#------------------------------------------------------------------------------ 