#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "0 is moved to 0.bak!"
rm -rf 0.bak
mv -f 0 0.bak

touch ${PWD##*/}.foam

runApplication blockMesh
runApplication topoSet
runApplication subsetMesh cut1 -patch walls -overwrite
cp -r 0.bak 0
# runApplication extrudeMesh
# runApplication createPatch -overwrite
# cp -r 0.wedge 0
# runApplication setFields
# runApplication renumberMesh -overwrite
