#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove mesh logs
rm -f log.blockMesh
rm -f log.topoSet
rm -f log.subsetMesh
rm -f log.setFields
rm -f log.decomposePar
rm -rf processor*/